# Лабораторна робота 1. NumPy

**Тема:** основи роботи з бібліотекою NumPy, масиви, вектори та матриці.

### Правила роботи
- Виконуйте завдання послідовно.
- Для обчислень використовуйте можливості **NumPy**.
- Не замінюйте операції NumPy звичайними Python-циклами, якщо це прямо не вказано в умові.
- Після виконання кожного завдання виводьте отриманий результат.


## 0. Підготовка середовища

### Завдання 0
Імпортуйте бібліотеку NumPy з псевдонімом `np`. Виведіть версію встановленої бібліотеки NumPy.

In [ ]:
import numpy as np
print(f"Версія NumPy: {np.__version__}")


Версія NumPy: 2.1.3


## 1. Створення масивів NumPy

### Завдання 1
Створіть одновимірний NumPy-масив із чисел:
`[2, 4, 6, 8, 10]`.

Виведіть масив та його тип за допомогою `type()`.

In [ ]:
arr_1 = np.array([2, 4, 6, 8, 10])
print(arr_1)
print(type(arr_1))


[ 2  4  6  8 10]
<class 'numpy.ndarray'>


### Завдання 2
Створіть:
1. масив із 10 нулів;
2. масив із 8 одиниць;
3. масив із 6 елементів, усі значення яких дорівнюють `7`.

Використайте відповідні функції NumPy.

In [ ]:
zeros_arr = np.zeros(10)
ones_arr = np.ones(8)
sevens_arr = np.full(6, 7)

print("Нулі:", zeros_arr)
print("Одиниці:", ones_arr)
print("Сімки:", sevens_arr)


Нулі: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Одиниці: [1. 1. 1. 1. 1. 1. 1. 1.]
Сімки: [7 7 7 7 7 7]


### Завдання 3
Створіть масив цілих чисел від `1` до `20` включно.

Після цього створіть окремий масив парних чисел від `2` до `20`.

In [ ]:
arr_1_to_20 = np.arange(1, 21)
arr_evens = np.arange(2, 21, 2)

print("1-20:", arr_1_to_20)
print("Парні:", arr_evens)


1-20: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Парні: [ 2  4  6  8 10 12 14 16 18 20]


### Завдання 4
За допомогою `np.linspace()` створіть масив із **11 рівновіддалених чисел** від `0` до `1` включно.

In [ ]:
linspace_arr = np.linspace(0, 1, 11)
print(linspace_arr)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


### Завдання 5
Створіть матрицю розміром `3 × 4`, заповнену числами від `1` до `12`.

Спочатку створіть одновимірний масив, а потім змініть його форму.

In [ ]:
mat_3x4 = np.arange(1, 13).reshape(3, 4)
print(mat_3x4)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


## 2. Основні характеристики масивів

### Завдання 6
Для матриці, створеної у попередньому завданні, визначте та виведіть:
- кількість вимірів;
- форму;
- загальну кількість елементів;
- тип даних елементів.

Використайте атрибути `ndim`, `shape`, `size`, `dtype`.

In [ ]:
print("Кількість вимірів (ndim):", mat_3x4.ndim)
print("Форма (shape):", mat_3x4.shape)
print("Загальна кількість елементів (size):", mat_3x4.size)
print("Тип даних (dtype):", mat_3x4.dtype)

Кількість вимірів (ndim): 2
Форма (shape): (3, 4)
Загальна кількість елементів (size): 12
Тип даних (dtype): int64


### Завдання 7
Створіть масив:
`[1.2, 3.5, 5.7, 7.9]`.

Перетворіть його елементи на цілі числа за допомогою `astype()` та виведіть новий масив.

In [ ]:
float_arr = np.array([1.2, 3.5, 5.7, 7.9])
int_arr = float_arr.astype(int)
print(int_arr)


[1 3 5 7]


## 3. Індексація та зрізи

### Завдання 8
Створіть масив:
`[10, 20, 30, 40, 50, 60, 70, 80]`.

Виведіть:
1. перший елемент;
2. останній елемент;
3. елементи з індексами від `2` до `5` включно;
4. кожен другий елемент.

In [ ]:
arr_8 = np.array([10, 20, 30, 40, 50, 60, 70, 80])

print("Перший:", arr_8[0])
print("Останній:", arr_8[-1])
print("Індекси 2-5:", arr_8[2:6])
print("Кожен другий:", arr_8[::2])


Перший: 10
Останній: 80
Індекси 2-5: [30 40 50 60]
Кожен другий: [10 30 50 70]


### Завдання 9
Створіть матрицю:

```text
[[ 1,  2,  3,  4],
 [ 5,  6,  7,  8],
 [ 9, 10, 11, 12]]
```

Виведіть:
1. елемент `7`;
2. другий рядок;
3. третій стовпець;
4. підматрицю з останніх двох рядків і перших двох стовпців.

In [ ]:
mat_9 = np.array([
 [ 1,  2,  3,  4],
 [ 5,  6,  7,  8],
 [ 9, 10, 11, 12]
])

print("Елемент 7:", mat_9[1, 2])
print("Другий рядок:", mat_9[1, :])
print("Третій стовпець:", mat_9[:, 2])
print("Підматриця (останні 2 рядки, перші 2 стовпці):\n", mat_9[-2:, :2])


Елемент 7: 7
Другий рядок: [5 6 7 8]
Третій стовпець: [ 3  7 11]
Підматриця (останні 2 рядки, перші 2 стовпці):
 [[ 5  6]
 [ 9 10]]


### Завдання 10
Створіть масив чисел від `1` до `15`.

Замініть усі елементи з індексами від `5` до `9` включно на число `0`.

In [ ]:
arr_10 = np.arange(1, 16)
arr_10[5:10] = 0
print(arr_10)


[ 1  2  3  4  5  0  0  0  0  0 11 12 13 14 15]


## 4. Арифметичні операції та агрегатні функції

### Завдання 11
Створіть два масиви:

```python
a = [1, 2, 3, 4, 5]
b = [10, 20, 30, 40, 50]
```

Виконайте поелементно:
- додавання;
- віднімання;
- множення;
- ділення.

In [ ]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([10, 20, 30, 40, 50])

print("Додавання:", a + b)
print("Віднімання:", a - b)
print("Множення:", a * b)
print("Ділення:", a / b)


Додавання: [11 22 33 44 55]
Віднімання: [ -9 -18 -27 -36 -45]
Множення: [ 10  40  90 160 250]
Ділення: [0.1 0.1 0.1 0.1 0.1]


### Завдання 12
Для масиву:

`[4, 8, 15, 16, 23, 42]`

обчисліть:
- суму;
- середнє значення;
- мінімум;
- максимум;
- медіану;
- стандартне відхилення.

In [ ]:
arr_12 = np.array([4, 8, 15, 16, 23, 42])

print("Сума:", np.sum(arr_12))
print("Середнє:", np.mean(arr_12))
print("Мінімум:", np.min(arr_12))
print("Максимум:", np.max(arr_12))
print("Медіана:", np.median(arr_12))
print("Стандартне відхилення:", np.std(arr_12))


Сума: 108
Середнє: 18.0
Мінімум: 4
Максимум: 42
Медіана: 15.5
Стандартне відхилення: 12.315302134607444


### Завдання 13
Створіть матрицю:

```text
[[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]]
```

Обчисліть:
1. суму всіх елементів;
2. суму по кожному стовпцю;
3. суму по кожному рядку;
4. середнє значення по кожному стовпцю.

In [ ]:
mat_13 = np.array([
 [1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]
])

print("Сума всіх:", np.sum(mat_13))
print("Сума по стовпцях:", np.sum(mat_13, axis=0))
print("Сума по рядках:", np.sum(mat_13, axis=1))
print("Середнє по стовпцях:", np.mean(mat_13, axis=0))


Сума всіх: 45
Сума по стовпцях: [12 15 18]
Сума по рядках: [ 6 15 24]
Середнє по стовпцях: [4. 5. 6.]


### Завдання 14
Для масиву чисел від `1` до `10` обчисліть:
- квадрат кожного елемента;
- квадратний корінь кожного елемента;
- натуральний логарифм кожного елемента.

Використайте функції NumPy.

In [ ]:
arr_14 = np.arange(1, 11)

print("Квадрат:", np.square(arr_14))
print("Корінь:", np.sqrt(arr_14))
print("Логарифм:", np.log(arr_14))


Квадрат: [  1   4   9  16  25  36  49  64  81 100]
Корінь: [1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.         3.16227766]
Логарифм: [0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458 2.30258509]


## 5. Логічні операції та фільтрація

### Завдання 15
Створіть масив:

`[3, 7, 12, 18, 21, 25, 30, 34]`

За допомогою булевої маски виведіть:
1. усі числа, більші за `15`;
2. усі парні числа;
3. числа в діапазоні від `10` до `30` включно.

In [ ]:
arr_15 = np.array([3, 7, 12, 18, 21, 25, 30, 34])

print("> 15:", arr_15[arr_15 > 15])
print("Парні:", arr_15[arr_15 % 2 == 0])
print("Від 10 до 30:", arr_15[(arr_15 >= 10) & (arr_15 <= 30)])


> 15: [18 21 25 30 34]
Парні: [12 18 30 34]
Від 10 до 30: [12 18 21 25 30]


### Завдання 16
Для масиву:

`[-5, 3, -2, 8, -1, 10, 0]`

замініть усі від’ємні значення на `0`.

Не використовуйте цикл `for`.

In [ ]:
arr_16 = np.array([-5, 3, -2, 8, -1, 10, 0])
arr_16[arr_16 < 0] = 0
print(arr_16)


[ 0  3  0  8  0 10  0]


### Завдання 17
Створіть масив випадкових цілих чисел від `0` до `100` розміром `20`.

Порахуйте:
- скільки елементів більші за `50`;
- скільки елементів менші або дорівнюють `50`.

Для відтворюваності встановіть `np.random.seed(42)`.

In [ ]:
np.random.seed(42)
arr_17 = np.random.randint(0, 101, size=20)

print("Більші за 50:", np.sum(arr_17 > 50))
print("Менші або дорівнюють 50:", np.sum(arr_17 <= 50))

Більші за 50: 12
Менші або дорівнюють 50: 8


## 6. Зміна форми та об'єднання масивів

### Завдання 18
Створіть масив чисел від `1` до `24`.

Перетворіть його:
1. у матрицю `4 × 6`;
2. у матрицю `6 × 4`;
3. у тривимірний масив форми `2 × 3 × 4`.

Після кожного перетворення виведіть `shape`.

In [ ]:
arr_18 = np.arange(1, 25)

mat_4x6 = arr_18.reshape(4, 6)
print("Форма 4x6:", mat_4x6.shape)

mat_6x4 = arr_18.reshape(6, 4)
print("Форма 6x4:", mat_6x4.shape)

mat_2x3x4 = arr_18.reshape(2, 3, 4)
print("Форма 2x3x4:", mat_2x3x4.shape)


Форма 4x6: (4, 6)
Форма 6x4: (6, 4)
Форма 2x3x4: (2, 3, 4)


### Завдання 19
Створіть дві матриці:

```text
A = [[1, 2],
     [3, 4]]

B = [[5, 6],
     [7, 8]]
```

Об’єднайте їх:
1. вертикально;
2. горизонтально.

Використайте функції NumPy.

In [ ]:
A_19 = np.array([[1, 2], [3, 4]])
B_19 = np.array([[5, 6], [7, 8]])

print("Вертикально:\n", np.vstack((A_19, B_19)))
print("Горизонтально:\n", np.hstack((A_19, B_19)))

Вертикально:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Горизонтально:
 [[1 2 5 6]
 [3 4 7 8]]


### Завдання 20
Створіть матрицю `3 × 4` із числами від `1` до `12`.

Перетворіть її назад в одновимірний масив двома способами:
- за допомогою `flatten()`;
- за допомогою `ravel()`.

Порівняйте результати.

In [ ]:
mat_20 = np.arange(1, 13).reshape(3, 4)

arr_flatten = mat_20.flatten() # Створює копію масиву
arr_ravel = mat_20.ravel()     # Створює представлення (view), якщо можливо

print("Flatten:", arr_flatten)
print("Ravel:", arr_ravel)


Flatten: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Ravel: [ 1  2  3  4  5  6  7  8  9 10 11 12]


## 7. Дії з векторами

### Завдання 21
Дано два вектори:

```text
a = [2, 4, 6]
b = [1, 3, 5]
```

Знайдіть:
- суму векторів;
- різницю векторів;
- результат множення кожного вектора на число `3`.

In [ ]:
a_21 = np.array([2, 4, 6])
b_21 = np.array([1, 3, 5])

print("Сума:", a_21 + b_21)
print("Різниця:", a_21 - b_21)
print("Множення a на 3:", a_21 * 3)
print("Множення b на 3:", b_21 * 3)


Сума: [ 3  7 11]
Різниця: [1 1 1]
Множення a на 3: [ 6 12 18]
Множення b на 3: [ 3  9 15]


### Завдання 22
Для векторів:

```text
a = [1, 2, 3]
b = [4, 5, 6]
```

Обчисліть їх **скалярний добуток** двома способами:
1. за допомогою `np.dot()`;
2. за допомогою оператора `@`.

In [ ]:
a_22 = np.array([1, 2, 3])
b_22 = np.array([4, 5, 6])

print("Скалярний добуток (dot):", np.dot(a_22, b_22))
print("Скалярний добуток (@):", a_22 @ b_22)


Скалярний добуток (dot): 32
Скалярний добуток (@): 32


### Завдання 23
Для вектора:

```text
v = [3, 4]
```

обчисліть його евклідову норму.

Потім нормалізуйте вектор, тобто отримайте вектор одиничної довжини.

In [ ]:
v_23 = np.array([3, 4])
norm_v = np.linalg.norm(v_23)

print("Норма:", norm_v)
print("Нормалізований вектор:", v_23 / norm_v)


Норма: 5.0
Нормалізований вектор: [0.6 0.8]


### Завдання 24
Дано вектори:

```text
a = [1, 0, 0]
b = [0, 1, 0]
```

Знайдіть їх векторний добуток за допомогою `np.cross()`.

In [ ]:
a_24 = np.array([1, 0, 0])
b_24 = np.array([0, 1, 0])

print("Векторний добуток:", np.cross(a_24, b_24))


Векторний добуток: [0 0 1]


### Завдання 25
Дано два вектори:

```text
a = [1, 2]
b = [2, 1]
```

Обчисліть косинус кута між ними за формулою через скалярний добуток і норми векторів.

Додатково знайдіть сам кут у градусах.

In [ ]:
a_25 = np.array([1, 2])
b_25 = np.array([2, 1])

cos_theta = np.dot(a_25, b_25) / (np.linalg.norm(a_25) * np.linalg.norm(b_25))
angle_deg = np.degrees(np.arccos(cos_theta))

print("Косинус кута:", cos_theta)
print("Кут у градусах:", angle_deg)


Косинус кута: 0.7999999999999998
Кут у градусах: 36.86989764584404


## 8. Дії з матрицями

### Завдання 26
Дано матрицю:

```text
A = [[1, 2, 3],
     [4, 5, 6]]
```

Знайдіть транспоновану матрицю двома способами:
1. за допомогою `.T`;
2. за допомогою `np.transpose()`.

In [ ]:
A_26 = np.array([[1, 2, 3], [4, 5, 6]])

print("Транспонування через .T:\n", A_26.T)
print("Транспонування через np.transpose:\n", np.transpose(A_26))


Транспонування через .T:
 [[1 4]
 [2 5]
 [3 6]]
Транспонування через np.transpose:
 [[1 4]
 [2 5]
 [3 6]]


### Завдання 27
Дано матриці:

```text
A = [[1, 2],
     [3, 4]]

B = [[2, 0],
     [1, 2]]
```

Обчисліть:
1. поелементний добуток `A * B`;
2. матричний добуток `A @ B`.

Поясніть у коментарі до коду, чим відрізняються ці операції.

In [ ]:
A_27 = np.array([[1, 2], [3, 4]])
B_27 = np.array([[2, 0], [1, 2]])

# Поелементне множення: множить відповідні елементи на однакових позиціях
print("Поелементне множення:\n", A_27 * B_27)

# Матричне множення: рядки першої множаться на стовпці другої
print("Матричне множення:\n", A_27 @ B_27)


Поелементне множення:
 [[2 0]
 [3 8]]
Матричне множення:
 [[ 4  4]
 [10  8]]


### Завдання 28
Для матриці:

```text
A = [[4, 7],
     [2, 6]]
```

обчисліть:
- визначник;
- обернену матрицю.

Перевірте результат, помноживши початкову матрицю на обернену.

In [ ]:
A_28 = np.array([[4, 7], [2, 6]])

det_A = np.linalg.det(A_28)
inv_A = np.linalg.inv(A_28)

print("Визначник:", det_A)
print("Обернена матриця:\n", inv_A)
print("Перевірка (A @ A_inv):\n", np.round(A_28 @ inv_A))


Визначник: 10.000000000000002
Обернена матриця:
 [[ 0.6 -0.7]
 [-0.2  0.4]]
Перевірка (A @ A_inv):
 [[ 1. -0.]
 [ 0.  1.]]


### Завдання 29
Розв’яжіть систему лінійних рівнянь за допомогою NumPy:

```text
2x +  y = 5
 x + 3y = 6
```

Сформуйте матрицю коефіцієнтів `A` і вектор правих частин `b`.

Використайте `np.linalg.solve()`.

In [ ]:
# 2x + y = 5
# x + 3y = 6
A_29 = np.array([[2, 1], [1, 3]])
b_29 = np.array([5, 6])

x_29 = np.linalg.solve(A_29, b_29)
print("Розв'язок (x, y):", x_29)

Розв'язок (x, y): [1.8 1.4]


### Завдання 30
Створіть одиничну матрицю розміром `4 × 4`.

Перевірте властивість одиничної матриці: помножте на неї довільну матрицю `4 × 4` та порівняйте результат з початковою матрицею.

In [ ]:
I_30 = np.eye(4)
random_mat = np.random.randint(1, 10, size=(4, 4))

print("Одинична матриця:\n", I_30)
print("Результат множення:\n", random_mat @ I_30)
print("Чи збігаються:", np.allclose(random_mat, random_mat @ I_30))

Одинична матриця:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Результат множення:
 [[2. 5. 1. 6.]
 [9. 1. 3. 7.]
 [4. 9. 3. 5.]
 [3. 7. 5. 9.]]
Чи збігаються: True


## 9. Broadcasting (операція трансляції)

### Завдання 31
Створіть матрицю:

```text
A = [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]]
```

Додайте число `10` до кожного її елемента.

In [ ]:
A_31 = np.array([
 [1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]
])

print("Додавання 10:\n", A_31 + 10)


Додавання 10:
 [[11 12 13]
 [14 15 16]
 [17 18 19]]


### Завдання 32
До матриці:

```text
A = [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]]
```

додайте вектор:

```text
v = [10, 20, 30]
```

Проаналізуйте, як NumPy застосував broadcasting.

In [ ]:
A_32 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
v_32 = np.array([10, 20, 30])

# Broadcasting автоматично розширив одновимірний масив (вектор) v_32
# до розмірів матриці A_32 та додав його до кожного рядка матриці.
print("Результат:\n", A_32 + v_32)


Результат:
 [[11 22 33]
 [14 25 36]
 [17 28 39]]


### Завдання 33
Нормалізуйте **кожен стовпець** матриці:

```text
A = [[10, 20, 30],
     [20, 30, 40],
     [30, 40, 50]]
```

за формулою:

\[
z = \frac{x - \mu}{\sigma}
\]

де `μ` — середнє значення стовпця, `σ` — стандартне відхилення стовпця.

Не використовуйте цикл `for`.

In [ ]:
A_33 = np.array([
 [10, 20, 30],
 [20, 30, 40],
 [30, 40, 50]
])

mu = np.mean(A_33, axis=0)
sigma = np.std(A_33, axis=0)
Z = (A_33 - mu) / sigma

print("Нормалізована матриця:\n", Z)


Нормалізована матриця:
 [[-1.22474487 -1.22474487 -1.22474487]
 [ 0.          0.          0.        ]
 [ 1.22474487  1.22474487  1.22474487]]


## 10. Випадкові дані

### Завдання 34
Встановіть `np.random.seed(42)` та створіть:
1. 10 випадкових цілих чисел від `1` до `100`;
2. матрицю `3 × 3` випадкових чисел від `0` до `1`;
3. 1000 значень із нормального розподілу.

Для третього масиву обчисліть середнє та стандартне відхилення.

In [ ]:
np.random.seed(42)
ints_34 = np.random.randint(1, 101, size=10)
rand_mat_3x3 = np.random.rand(3, 3)
normal_dist = np.random.randn(1000)

print("10 випадкових чисел:", ints_34)
print("Матриця 3x3:\n", rand_mat_3x3)
print("Середнє норм. розподілу:", np.mean(normal_dist))
print("Ст. відхилення норм. розподілу:", np.std(normal_dist))


10 випадкових чисел: [52 93 15 72 61 21 83 87 75 75]
Матриця 3x3:
 [[0.86617615 0.60111501 0.70807258]
 [0.02058449 0.96990985 0.83244264]
 [0.21233911 0.18182497 0.18340451]]
Середнє норм. розподілу: 0.02216865975826456
Ст. відхилення норм. розподілу: 0.9792284455184356


### Завдання 35
Змоделюйте оцінки 30 студентів — випадкові цілі числа від `0` до `100`.

Визначте:
- середню оцінку;
- медіану;
- найвищу та найнижчу оцінки;
- кількість студентів, які отримали не менше `60`;
- відсоток студентів, які отримали не менше `90`.

In [ ]:
scores = np.random.randint(0, 101, size=30)

print("Середня оцінка:", np.mean(scores))
print("Медіана:", np.median(scores))
print("Найвища:", np.max(scores))
print("Найнижча:", np.min(scores))
print("Кількість >= 60:", np.sum(scores >= 60))
print("Відсоток >= 90:", np.mean(scores >= 90) * 100, "%")


Середня оцінка: 44.4
Медіана: 43.5
Найвища: 99
Найнижча: 2
Кількість >= 60: 8
Відсоток >= 90: 6.666666666666667 %


## 11. Підсумкові завдання

### Завдання 36
Дано результати продажів трьох товарів за чотири місяці:

```text
sales = [[120, 150, 170, 160],
         [80,  90,  100, 110],
         [200, 180, 210, 230]]
```

Рядки — товари, стовпці — місяці.

Визначте:
1. загальний обсяг продажів кожного товару;
2. загальний обсяг продажів у кожному місяці;
3. товар із найбільшими сумарними продажами;
4. місяць із найбільшим загальним обсягом продажів;
5. середній обсяг продажів кожного товару.

In [ ]:
sales = np.array([
 [120, 150, 170, 160],
 [80,  90,  100, 110],
 [200, 180, 210, 230]
])

print("Продажі кожного товару:", np.sum(sales, axis=1))
print("Продажі в кожному місяці:", np.sum(sales, axis=0))
print("Індекс товару з макс продажами:", np.argmax(np.sum(sales, axis=1)))
print("Індекс місяця з макс продажами:", np.argmax(np.sum(sales, axis=0)))
print("Середній обсяг по кожному товару:", np.mean(sales, axis=1))


Продажі кожного товару: [600 380 820]
Продажі в кожному місяці: [400 420 480 500]
Індекс товару з макс продажами: 2
Індекс місяця з макс продажами: 3
Середній обсяг по кожному товару: [150.  95. 205.]


### Завдання 37
Створіть квадратну матрицю `5 × 5` із випадкових цілих чисел від `1` до `20`.

Виконайте:
1. знайдіть суму головної діагоналі;
2. знайдіть суму побічної діагоналі;
3. знайдіть максимальний елемент кожного рядка;
4. знайдіть мінімальний елемент кожного стовпця;
5. замініть усі елементи, менші за середнє значення всієї матриці, на `0`.

In [ ]:
mat_37 = np.random.randint(1, 21, size=(5, 5))

print("Сума головної діагоналі:", np.trace(mat_37))
print("Сума побічної діагоналі:", np.trace(np.fliplr(mat_37)))
print("Максимум кожного рядка:", np.max(mat_37, axis=1))
print("Мінімум кожного стовпця:", np.min(mat_37, axis=0))

mean_val = np.mean(mat_37)
mat_37[mat_37 < mean_val] = 0
print(f"Матриця після заміни значень < {mean_val:.2f}:\n", mat_37)


Сума головної діагоналі: 25
Сума побічної діагоналі: 38
Максимум кожного рядка: [19 17 20 19 15]
Мінімум кожного стовпця: [2 1 2 9 2]
Матриця після заміни значень < 9.96:
 [[ 0  0 10 19  0]
 [15  0  0 12 17]
 [20  0  0 12 20]
 [18 17 19  0  0]
 [ 0  0  0 15  0]]


### Завдання 38
Дано матрицю ознак трьох об’єктів:

```text
X = [[2, 4, 6],
     [1, 3, 5],
     [5, 7, 9]]
```

Обчисліть **евклідову відстань** між:
- першим і другим рядком;
- першим і третім рядком;
- другим і третім рядком.

Використайте операції NumPy та `np.linalg.norm()`.

In [ ]:
X = np.array([
 [2, 4, 6],
 [1, 3, 5],
 [5, 7, 9]
])

print("Відстань рядок 1 і 2:", np.linalg.norm(X[0] - X[1]))
print("Відстань рядок 1 і 3:", np.linalg.norm(X[0] - X[2]))
print("Відстань рядок 2 і 3:", np.linalg.norm(X[1] - X[2]))


Відстань рядок 1 і 2: 1.7320508075688772
Відстань рядок 1 і 3: 5.196152422706632
Відстань рядок 2 і 3: 6.928203230275509


### Завдання 39
Створіть матрицю `4 × 4` із довільних цілих чисел.

Для кожного рядка знайдіть його норму та створіть нову матрицю, у якій кожен рядок нормалізований до одиничної довжини.

Спробуйте виконати завдання без циклів.

In [ ]:
mat_39 = np.random.randint(1, 10, size=(4, 4))

row_norms = np.linalg.norm(mat_39, axis=1, keepdims=True)
normalized_mat = mat_39 / row_norms

print("Початкова матриця:\n", mat_39)
print("Нормалізована матриця:\n", normalized_mat)


Початкова матриця:
 [[4 6 7 3]
 [3 6 3 2]
 [8 5 1 3]
 [8 4 7 2]]
Нормалізована матриця:
 [[0.38138504 0.57207755 0.66742381 0.28603878]
 [0.3939193  0.7878386  0.3939193  0.26261287]
 [0.80403025 0.50251891 0.10050378 0.30151134]
 [0.69368798 0.34684399 0.60697698 0.17342199]]


### Завдання 40
Створіть матрицю коефіцієнтів і вектор правих частин для системи:

```text
 x + 2y +  z =  9
2x +  y -  z =  8
3x -  y + 2z =  3
```

1. Розв’яжіть систему за допомогою `np.linalg.solve()`.
2. Перевірте знайдений розв’язок матричним множенням `A @ x`.
3. Порівняйте результат із вектором `b`.

In [ ]:
A_40 = np.array([
 [1,  2,  1],
 [2,  1, -1],
 [3, -1,  2]
])
b_40 = np.array([9, 8, 3])

x_40 = np.linalg.solve(A_40, b_40)
print("Розв'язок:", x_40)

check = A_40 @ x_40
print("A @ x:", check)
print("Порівняння з b:", np.allclose(check, b_40))


Розв'язок: [ 2.22222222  3.44444444 -0.11111111]
A @ x: [9. 8. 3.]
Порівняння з b: True


---

## Самоперевірка

Після виконання роботи студент повинен уміти:
- створювати та перетворювати NumPy-масиви;
- використовувати індексацію та зрізи;
- виконувати векторизовані арифметичні операції;
- застосовувати агрегатні функції;
- використовувати булеві маски;
- змінювати форму та об'єднувати масиви;
- виконувати основні дії з векторами;
- виконувати основні операції з матрицями;
- застосовувати broadcasting;
- використовувати функції `numpy.linalg` для задач лінійної алгебри.
